---

# all
- hosts: all
  gather_facts: yes
  sudo: yes

  tasks:

  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{ item }}" state=present
    when: "hostvars[item]['ansible_host'] is defined"
    with_items: groups['all']

  - name: Install ntp
    yum: name=ntp state=present

  - name: start ntpd
    service: name=ntpd state=started
