---

# all
- hosts: all
  gather_facts: yes
  become: true

  tasks:

  - name: Check for /dev/sdb
      command: parted -s /dev/sdb print 2
      register: sdb
      failed_when: sdb.rc is not defined
      changed_when: >
        sdb.stdout == "Error: Partition doesn't exist."
    - name: Create /dev/sdb
      #command: parted -s /dev/xvda mkpart primary 21.5G 100%
    - lvol: vg=datavg lv=data size=128 pvs=/dev/sdb
      when: sdb.rc != 0

    # - name: Ensure data mountpoint exists
    #   file: path=/data state=directory owner=root group=root mode=0755

    - name: Mount data LV
      mount: name=/data src=/dev/datavg/data fstype=ext4
             state=mounted opts="errors=remount-ro,noatime,barrier=0"
             dump=0 passno=2
